DEBUG:root:Order:pID: 2 total ships: 100.0 fleet size: 6.0
ERROR:root:Error in bot.
Traceback (most recent call last):
  File "opponent_bots/spread_bot.py", line 79, in <module>
    do_turn(planet_wars)
  File "opponent_bots/spread_bot.py", line 66, in do_turn
    spread(state)
  File "opponent_bots/spread_bot.py", line 28, in spread
    issue_order(state, my_planet.ID, target_planet.ID, required_ships)
  File "C:\Users\AJmet\Documents\GameAI\BehaviorTrees\planet_wars.py", line 25, in issue_order
    stdout.flush()
OSError: [Errno 22] Invalid argument
